version: 2.1

orbs:
  node: circleci/node@7.1.0

jobs:
  deploy:
    docker:
      - image: cimg/node:24.3.0
    steps:
      - checkout

      - run:
          name: Install Python
          command: |
            sudo apt-get update
            sudo apt-get install -y python3 python3-venv python3-pip unzip curl

      - run:
          name: Install AWS CLI v2
          command: |
            curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
            unzip awscliv2.zip
            sudo ./aws/install
            aws --version

      - run:
          name: Install AWS CDK
          command: npm install -g aws-cdk

      - run:
          name: Set up Python environment
          command: |
            cd cdk
            python3 -m venv .venv
            source .venv/bin/activate
            pip install -r requirements.txt

      - run:
          name: Verify AWS credentials
          command: aws sts get-caller-identity

      - run:
          name: Bootstrap CDK
          command: |
            cd cdk
            source .venv/bin/activate
            cdk bootstrap

      - run:
          name: Deploy CDK stacks
          command: |
            cd cdk
            source .venv/bin/activate
            cdk deploy --all --require-approval never

      - run:
          name: Output deployment info
          command: |
            echo "Deployment completed successfully"
            echo "Check AWS Console for deployed resources"

  destroy:
    docker:
      - image: cimg/node:24.3.0
    steps:
      - checkout

      - run:
          name: Install Python
          command: |
            sudo apt-get update
            sudo apt-get install -y python3 python3-venv python3-pip unzip curl

      - run:
          name: Install AWS CLI v2
          command: |
            curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
            unzip awscliv2.zip
            sudo ./aws/install
            aws --version
            
      - run:
          name: Install node.js and CDK
          command: npm install -g aws-cdk

      - run:
          name: Set up Python environment
          command: |
            cd cdk
            python3 -m venv .venv
            source .venv/bin/activate
            pip install -r requirements.txt

      - run:
          name: Verify AWS credentials
          command: aws sts get-caller-identity

      - run:
          name: Destroy CDK stacks
          command: |
            cd cdk
            source .venv/bin/activate
            cdk destroy --all --force

      - run:
          name: Output teardown info
          command: |
            echo "Teardown completed successfully"
            echo "Resources have been destroyed"


workflows:
  deploy_app:
    jobs:
      - deploy

  # Optional: scheduled destroy job (e.g., Every Friday at 13:30 UTC)
  scheduled_teardown:
    triggers:
      - schedule:
          cron: "20 14 * * 5"  # Every Friday at 13:30 UTC
          filters:
            branches:
              only:
                - main
    jobs:
      - destroy
